#  server.port=8081
#    spring.application.name=nacos-provider
#    spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
#    management.endpoints.web.exposure.include=*
server:
  port: 9004

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 #nacos\u4F5C\u4E3A\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740

management:
  endpoints:
    web:
      exposure:
        include: '*'


