server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 202095@Wrm
  profiles:
    active: dev

  cloud:
    zookeeper:
      connect-string: localhost:2181
