server:
  port: 8004

#服务别名-----注册到zookeeper注册中心的名称
spring:
  application:
    name: cloud-provider-payment
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      driver-class-name: com.mysql.jdbc.Driver          # mysql驱动包
      url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 202095@Wrm
  profiles:
      active: dev

  cloud:
    zookeeper:
      connect-string: localhost:2181
